### ISSUE TITLE
Update texlive with GA actions

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [dante-ev/docker-texlive#41]
Hi! Thanks for this docker image!

I would like to know how to update the texlive version in danteev/texlive inside a Github actions workflow?

This issue is related to https://github.com/fmarotta/kaobook/issues/157

Thank you in advance!

**Comment by koppor** [comment]
You can use the `edge` tag if you use the docker image directly. See https://hub.docker.com/r/danteev/texlive/tags?page=1&ordering=last_updated for the list of all tags.

Regarding the action, it is also possible to use `edge`. I would really recommend using the `edge` tag to enable faster builds (with the hope that GitHub caches the images).

**Comment by RemDelaporteMathurin** [comment]
Hi @koppor thanks for reaching out!

I've updated the tag in my GA action file (see below) but I'm afraid the problem in https://github.com/fmarotta/kaobook/issues/157 isn't fixed. 

This is my GA file:

```yml
name: Build LaTeX document

# Triggers the workflow on push or pull request events
on: [push, pull_request]
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
```

Any thoughts?
